### ISSUE TITLE
Problem with SPI

### ISSUE THREAD

**Issue by Kuritto** [pedestrian0423/DW1000_Raspi_Python_library#2] opened 2021-10-26 12:19 UTC
Hello,
I'm trying to test a DW1000 module, so I tried to write my own code. Unfortunately it dosen't work, so I find your's library and I have the same problem as with my code. When I'm trying to connect module with RPi4 by SPI it returns Device ID as 7F7F instead of DECA.
Do you have any idea why it isn't work?
I would be grateful for your's help
![SPI_Error](https://user-images.githubusercontent.com/93198238/138877302-0f0d4aa4-b9a1-4e4c-b727-e318c924c3b8.PNG)
.

**Comment by pedestrian0423** [comment] 2021-10-29 18:42
Hi,
The problem might be incurred from "wiring problem" or "byte array processing error".
All of the values presented at your log shows 0111(7), 1111(15), 01111111(127), 7F, 7F7F.
If you could provide wiring diagram of your hardware setup, It'll be helpful to understanding what the problem is.

**Comment by marcusobrien** [comment] 2021-12-31 08:44
@pedestrian0423 - Could you provide the connections between the Pi 3 and the DWS1000 please.

**Comment by pedestrian0423** [comment] 2021-12-31 19:00
@marcusobrien Please check the datasheet of DW1000 and the pin out of the raspberry pi first.
* DW1000 - https://www.decawave.com/sites/default/files/dwm1001_datasheet.pdf
* RPi3       - https://pinout.xyz/#

**Comment by pedestrian0423** [comment] 2022-04-09 11:32
Since no other questions over three months, I close this issue.

**Closed as completed by pedestrian0423** 2022-04-09 11:32 UTC
